### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by dajver** [JamesDunne/android-wallpaper-animator#1]
How to change your class to getting images not from file? Sor example from array of drawables? Like int array = {R.drawable.one, R.drawable.two, R.drawable.three}; ? Cuz i don't understand how to change you code,it too difficult for me.

Thanks for answer

**Comment by JamesDunne** [comment]
Sorry, I don't know enough android to help you. I've abandoned this project because it does not work due to stringent memory requirements. You're not likely to make great progress using this as a starting point if you need lots of drawables in memory like I did. Android will kill your application if you use too much memory.

**Comment by dajver** [comment]
I see. I need display 120 images ) So... this suitable for me...
Thanks for your answer.

**Comment by JamesDunne** [comment]
Sure. What you probably want to do is use OpenGL to load your images as textures since I don't think texture memory counts against your application's memory usage. That's pretty much the only option left.
